Vagrant.configure("2") do |config|
  names = {"r1" => 10000, "r2" => 20000, "r3" => 30000}
  names.each_pair do |name, offset|
    config.vm.define name do |machine|
      machine.vm.box = "debian/jessie64"
      machine.vm.network "private_network", type: "dhcp"

      machine.vm.network "forwarded_port", guest: 8080, host: offset + 8080, host_ip: "127.0.0.1"
      machine.vm.network "forwarded_port", guest: 6379, host: offset + 6379, host_ip: "127.0.0.1"
      machine.vm.network "forwarded_port", guest: 6380, host: offset + 6380, host_ip: "127.0.0.1"
      machine.vm.network "forwarded_port", guest: 6381, host: offset + 6381, host_ip: "127.0.0.1"

      next unless name == names.keys.last

      machine.vm.provision "ansible" do |ansible|
        ansible.verbose = "v"
        ansible.playbook = "site.yml"
        ansible.limit = 'all'
        ansible.sudo = true
        ansible.groups = {
          "redis" => names.keys.sort,
        }
      end
    end
  end
end
